codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "migrations/**/*"
  - "venv/**/*"
  - ".venv/**/*"
  - "ai_demo_frontend/**/*"
  - "app/ai/**/*"
  - "etl_build_index.py"
  - "scripts/**/*"
