INSERT INTO menu_item (title, description, image_url, origin, category, tags, flavor_profile, dietary_restrictions, price) VALUES
('Black Forest', '黑森林蛋糕', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/black_forest.jpg', 'french', 'pastry',
 ARRAY['cake','forest','chocolate'], ARRAY[]::text[], ARRAY['liquor'], 89.00),
('Italian Macarons', '意式马卡龙', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/macarons.jpg', 'french', 'pastry',
 ARRAY['macaron','almond'], ARRAY[]::text[], ARRAY['tree nuts', 'gluten free'], 69.00),
('Cedric Grolet', '法式甜品慕斯', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/cedric_grolet.jpg', 'french', 'pastry',
 ARRAY['mousse','french_pastry'], ARRAY[]::text[], ARRAY[]::text[], 99.00),
('Tiramisu', '提拉米苏', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/tiramisu.jpg', 'fusion', 'pastry',
 ARRAY['italian','coffee','cream'], ARRAY[]::text[], ARRAY[]::text[], 59.00),
('Egg Tart', '葡式蛋挞', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/egg_tart.jpg', 'chinese', 'pastry',
 ARRAY['tart','egg','pastry'], ARRAY[]::text[], ARRAY[]::text[], 39.00),
('Mango/Banana/Durian Pancake', '芒果班戟', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/mango_pancake.jpg', 'chinese', 'dessert',
 ARRAY['pancake','fruit'], ARRAY[]::text[], ARRAY[]::text[], 39.00),
('Tiger Skin Swiss Roll', '虎皮蛋糕', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/swiss_roll.jpg', 'chinese', 'pastry',
 ARRAY['roll_cake','swiss_roll'], ARRAY[]::text[], ARRAY[]::text[], 49.00),
('Tang-yuan', '汤圆', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/tang_yuan.jpg', 'chinese', 'dessert',
 ARRAY['rice_ball','mochi'], ARRAY[]::text[], ARRAY[]::text[], 39.00),
('Sticky Rice Tamale', '粽子', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/tamale.jpg', 'chinese', 'dessert',
 ARRAY['rice','sticky'], ARRAY[]::text[], ARRAY[]::text[], 59.00),
('Mooncake', '月饼', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/mooncake.jpg', 'chinese', 'dessert',
 ARRAY['sweet'], ARRAY[]::text[], ARRAY[]::text[], 59.00),
('Baileys Strawberry Cake', '百利甜酒草莓蛋糕', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/baileys.jpg', 'fusion', 'pastry',
 ARRAY['strawberry','cream'], ARRAY[]::text[], ARRAY['contains_alcohol','vegetarian'], 59.00),
('Blueberry Cake', '蓝莓巧克力蛋糕', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/blueberry.jpg', 'american', 'dessert',
 ARRAY['blueberry','cake'], ARRAY[]::text[], ARRAY[]::text[], 59.00),
('Mango Mousse Cake', '爱心芒果慕斯蛋糕', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/mango_mousse.jpg', 'fusion', 'pastry',
 ARRAY['mousse','mango'], ARRAY[]::text[], ARRAY[]::text[], 59.00),
('Strawberry Mousse Cake', '爱心草莓慕斯蛋糕', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/strawberry_mousse.jpg', 'fusion', 'pastry',
 ARRAY['mousse','strawberry'], ARRAY[]::text[], ARRAY[]::text[], 59.00),
('Watermelon Cake', '西瓜蛋糕', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/watermelon.jpg', 'fusion', 'pastry',
 ARRAY['watermelon','cake'], ARRAY[]::text[], ARRAY[]::text[], 199.00),
('Cream Puff (Vanilla, Coco or Mocha)', '泡芙（香草，可可，抹茶馅)', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/cream_puff.jpg', 'french', 'pastry',
 ARRAY['cream_puff','sweet'], ARRAY[]::text[], ARRAY[]::text[], 89.00),
('Ice Cream (Vanilla, Coco or Mocha)', '冰淇淋（香草，可可，抹茶馅)', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/ice_cream.jpg', 'french', 'pastry',
 ARRAY['cream_puff','sweet'], ARRAY[]::text[], ARRAY[]::text[], 89.00),
('Fruit Cake', '水果蛋糕', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/fruit_cake.jpg', 'fusion', 'pastry',
 ARRAY['cream_puff','sweet'], ARRAY[]::text[], ARRAY[]::text[], 89.00),
('Taro Cake', '芋泥蛋糕', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/taro_cake.jpg', 'chinese', 'pastry',
 ARRAY['taro','cake'], ARRAY[]::text[], ARRAY[]::text[], 69.00),
('Cookie', '饼干', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/cookie.jpg', 'american', 'dessert',
 ARRAY['cream_puff','sweet'], ARRAY[]::text[], ARRAY[]::text[], 49.00);


INSERT INTO menu_item (title, description, image_url, origin, category, tags, flavor_profile, dietary_restrictions, price) VALUES
('Chicken Wing', '韩式鸡翅', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/chicken_wing.jpg', 'korean', 'entree',
 ARRAY['chicken', 'deep fry'], ARRAY['spicy'], ARRAY[]::text[], 99.00),
('Steaming Fish', '清蒸鲈鱼', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/steaming_fish.jpg', 'chinese', 'entree',
 ARRAY['fish','steamed'], ARRAY[]::text[], ARRAY[]::text[], 99.00),
('Chongqing Noodles', '重庆小面', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/chongqing_noodles.jpg', 'chinese', 'entree',
 ARRAY['noodles','spicy'], ARRAY[]::text[], ARRAY[]::text[], 59.00),
('Beef Noodles', '李先生加州牛肉面', '', 'chinese', 'entree',
 ARRAY['noodles','spicy'], ARRAY[]::text[], ARRAY[]::text[], 59.00),
('Sour Beef Soup', '酸汤肥牛', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/sour_beef_soup.jpg', 'chinese', 'entree',
 ARRAY['soup','beef'], ARRAY[]::text[], ARRAY[]::text[], 49.00),
('Spicy Chicken', '辣子鸡', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/spicy_chicken.jpg', 'chinese', 'entree',
 ARRAY['chicken','sichuan','spicy'], ARRAY[]::text[], ARRAY[]::text[], 59.00),
('Griddle Cooked Mushrooms', '干锅茶树菇', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/mushrooms.jpg', 'chinese', 'entree',
 ARRAY['mushroom','stir_fry'], ARRAY[]::text[], ARRAY[]::text[], 59.00),
('Kung-Pao Chicken', '宫保鸡丁', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/kungpao.jpg', 'chinese', 'entree',
 ARRAY['chicken','kungpao','spicy'], ARRAY[]::text[], ARRAY['contains_nuts'], 39.00),
('Fish (Grilled)', '烤鱼', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/grill_fish.jpg', 'chinese', 'entree',
 ARRAY['fish','grilled'], ARRAY[]::text[], ARRAY[]::text[], 99.00),
('Crystal Shrimp Dumpling', '水晶虾饺', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/dumpling.jpg', 'chinese', 'entree',
 ARRAY['dumpling','shrimp'], ARRAY[]::text[], ARRAY[]::text[], 69.00),
('Baozi', '素菜包子', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/bum.jpg', 'chinese', 'entree',
 ARRAY['bun','steamed'], ARRAY[]::text[], ARRAY[]::text[], 69.00),
('Griddle Pork Intestines', '干锅肥肠', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/intestines.jpg', 'chinese', 'entree',
 ARRAY['pork','stir_fry','intestine'], ARRAY[]::text[], ARRAY[]::text[], 59.00),
('Yuxiang Shredded Pork', '鱼香肉丝', 'https://yorkiebakery-image.s3.us-west-2.amazonaws.com/menu/shredded_pork.jpg', 'chinese', 'entree',
 ARRAY['pork','yuxiang'], ARRAY[]::text[], ARRAY[]::text[], 49.00);